### ISSUE TITLE
Connecting to custom substrate node

### ISSUE THREAD

**Issue by 6636345e** [polkascan/explorer#14]
Hello.

I have a seperate customized substrate node in a server and when I try to connect the endpoints using Polkscan explorer, it does not want to connect to the exposed endpoints.
*Seen screenshots below: 

- I commented the line ```- SUBSTRATE_RPC_URL=ws://substrate-node:9944``` since  I have customized node running on the server.
- Changed to ```- SUBSTRATE_RPC_URL=ws://10.11.101.23:9944```
<img width="1137" alt="Screenshot 2022-11-08 at 12 07 36" src="https://user-images.githubusercontent.com/44494722/200537098-e633bb1b-6298-4137-a9c5-86b3b2f7e33d.png">

- After the explorer run, on the browser it does not connect to the explosed endpoints from the node.
- Instead, it shows the display in the screenshot below.
<img width="1499" alt="Screenshot 2022-11-08 at 12 07 07" src="https://user-images.githubusercontent.com/44494722/200537668-1bfd3e72-b9d1-4fa3-81f9-ae00cbb2617c.png">

- Any advice on this?

**Comment by 6636345e** [comment]
- Thanks for the response!
- But I have changed 'Local node URL' to 'ws://10.11.101.23:9944' but  it still display "connecting". 
- Check screenshots below
<img width="1451" alt="Screenshot 2022-11-08 at 14 20 03" src="https://user-images.githubusercontent.com/44494722/200562545-c4c79da1-d1eb-4d65-b70d-747c682cb9bc.png">

<img width="1326" alt="Screenshot 2022-11-08 at 14 21 11" src="https://user-images.githubusercontent.com/44494722/200562574-b3a3096c-a029-4aa8-8d1e-2b60f3069e24.png">

**Comment by 6636345e** [comment]
Also when I run the Substrate node locally, it does connect. But not on the server which is the goa, running the node and explorer on the server.

**Comment by arjanz** [comment]
Have you run the Substrate node with `--ws-external --rpc-cors=all` to allow external connections?

**Comment by 6636345e** [comment]
Yes, substrate node with ```./target/release/node-template --ws-external --rpc-cors=all```.
I am not sure if it's because I am running it as Docker
```docker-compose up --build``` and I noticed that the DOCKER image is pulled from  ```arjanz/substrate-node-template:latest```

**Comment by arjanz** [comment]
> * Thanks for the response!
> * But I have changed 'Local node URL' to 'ws://10.11.101.23:9944' but  it still display "connecting".
> * Check screenshots below

I still see `ws://127.0.0.1:9944` in stead of `ws://10.11.101.23:9944` in your screenshot, I think because it's stored in your browser's local storage. What if you manually replace it there with `ws://10.11.101.23:9944?`



> I noticed that the DOCKER image is pulled from `arjanz/substrate-node-template:latest` but I want it to connect to the local substrate node not use the node from the docker image.

Yes this was actually temporary hosted from my personal Docker hub account, thanks for noticing, I'll replace it with the Polkascan one as it should.

**Comment by 6636345e** [comment]
> I still see ws://127.0.0.1:9944 in stead of ws://10.11.101.23:9944 in your screenshot, I think because it's stored in your browser's local storage. What if you manually replace it there with ws://10.11.101.23:9944?

Oh yes thank you, it was stored in my browser's local storage, thank you now it connects 

> Yes this was actually temporary hosted from my personal Docker hub account, thanks for noticing, I'll replace it with the Polkascan one as it should.

 Glad I helped while asking help myself, thanks for assistance.
- I cleared my browser and changed "Local node URL" to my substrate node endpoints
