### ISSUE TITLE
How to configure the docker-compose.yml for AWS RDS

### ISSUE THREAD

**Issue by chandanchoudhury0809** [polkascan/explorer#15]
After configuring docker-compose.yml for AWS RDS with the correct values, tables are not created in the database, and block data is missing. This means writing to DB is not working.

Can you share some documents on how to setup or configure docker-compose.yml for AWS RDS (MySQL)?

<img width="1099" alt="Screenshot 2022-11-10 at 9 45 37 AM" src="https://user-images.githubusercontent.com/67783833/201000187-4595c85f-325c-46ba-a162-b24e865973f6.png">

**Comment by chandanchoudhury0809** [comment]
I am using external hosted SUBSTRATE_RPC_URL. If I am running all things locally writing to DB is working. But I need to connect to external DB. and external SUBSTRATE_RPC_URL.

**Comment by wouterter** [comment]
Are you still having issues? If so, can you show us your log files? It should be able to work on an external DB. Are you perhaps having firewall or connection issues? Have you set proper permissions on the database server?

**Comment by chandanchoudhury0809** [comment]
Its working fine now. I fixed it by configuring DB properly.
