### ISSUE TITLE
About start the explorer project in local environment

### ISSUE THREAD

**Issue by VegeBun-csj** [polkascan/explorer#2]
how can i setup the explorer in my local environment but not in docker, so that i can debug it easily

**Comment by arjanz** [comment]
It is described in the readme of the submodules like: https://github.com/polkascan/harvester/tree/main#running-locally and https://github.com/polkascan/explorer-ui/tree/main#build-manually

Or you can have a look into the `Dockerfile` of the submodules to give a specific set of instructions how to run them locally

**Comment by didiermis** [comment]
@arjanz do i need to do both tutorials? I was trying the first one, https://github.com/polkascan/harvester/tree/main#running-locally, but when I run "alembic upgrade head" throws an error: 
![image](https://user-images.githubusercontent.com/62629075/188064090-a2236787-14bd-4ea4-9900-414ed87845d5.png)

**Comment by arjanz** [comment]
@didiermis Is your MySQL running locally as well or still in the Docker container? You might have to check if the port is still valid, because it is mapped as `33061` on the host machine (See: https://github.com/polkascan/explorer/blob/main/docker-compose.yml#L98)

**Comment by wouterter** [comment]
This conversation seems to have ended. I'm closing this issue.
